show databases;
CREATE TABLE FORNECEDOR (
  NOME VARCHAR(255) NOT NULL,
  CONTATO VARCHAR(20) NULL,
  CNPJ VARCHAR(45) NULL,
  ENDERECO VARCHAR(255) NULL,
  PRODUTO VARCHAR(255) NULL,
  CODIGO NUMERIC NOT NULL,
  VALOR VARCHAR(255) NULL
);

CREATE TABLE FORNECEDOR_has_PRODUTO (
  PRODUTO_QUANT NUMERIC NOT NULL,
  PRIMARY KEY(PRODUTO_QUANT),
  INDEX FORNECEDOR_has_PRODUTO_FKIndex2(PRODUTO_QUANT)
);

CREATE TABLE NOTA_FISCAL (
  N_NF  NUMERIC NOT NULL ,
  PRODUTO_QUANT NUMERIC NOT NULL,
  DATA_ENT DATE NULL,
  DATA_SAIDA DATE NULL,
  QTD NUMERIC NULL,
  VALOR VARCHAR(255) NULL,
  PRODUTO VARCHAR(45) NULL,
  HORA VARCHAR(20) NULL,
  PRIMARY KEY(N_NF ),
  INDEX NOTA_FISCAL_FKIndex1(PRODUTO_QUANT)
);

CREATE TABLE PRODUTO_1VALOR(
  QUANT NUMERIC NOT NULL,
  NOME VARCHAR(45) NULL,
  FORN VARCHAR(45) NULL,
  DT_ENTR DATE NULL,
  VALIDADE NUMERIC NULL,
  DESCR VARCHAR(45) NULL,
  VALOR NUMERIC NOT NULL,
  COD VARCHAR(255) NULL,
  PRIMARY KEY(QUANT)
);

INSERT INTO produtos (QUANT,NOME,FORN,DT_ENTR,VALIDADE,DESCR,VALOR,COD) VALUES ("10 "Massa de pastel", "Massa da feira", "01/11/2022", "01/12/2022", "Massa de pastel pré pronta", "R$8", "1100");
INSERT INTO produtos (QUANT,NOME,FORN,DT_ENTR,VALIDADE,DESCR,VALOR,COD) VALUES ("2", "Mussarela", "Confiança", "01/11/2022", "31/12/2022", "Mussarela sadia", "R$34,90", "001101");
INSERT INTO produtos (QUANT,NOME,FORN,DT_ENTR,VALIDADE,DESCR,VALOR,COD) VALUES ("4", "Presunto", "Confiança", "01/11/2022", "01/01/2023", "Presunto defumado seara", "R$24,96", "001102");

